[music]
startrng = [85, 5, 9, 1]         # [%]  Chance for each playlist to occur in the mix at the lowest intensity
endrng = [10, 20, 60, 10]          # [%]  Chance for each playlist to occur in the mix at the highest intensity
