[music]
startrng = [85, 5, 10]         # [%]  Chance for each playlist to occur in the mix at the lowest intensity
endrng = [10, 20, 70]          # [%]  Chance for each playlist to occur in the mix at the highest intensity
